version: '3'

volumes:
  opensearchdata01:
    driver: local
  suricatalogs:
    driver: local
  zabbix:
    driver: local
  db-data:
    driver: local
  nginx:
    driver: local      

networks:
  insm-net:
    name: insm-net
    external: true
services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./suricata/var/log/suricata:/suricata
    networks:
      insm-net:
        ipv4_address: 192.168.1.30

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    build:
      context: ./opensearch
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearchdata01:/usr/share/opensearch/data 
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      insm-net:
        ipv4_address: 192.168.1.50
  
  opensearch-dashboards:
    image: opensearch-dashboards-no-security
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_PLUGIN=true" 
    networks:
      insm-net:
        ipv4_address: 192.168.1.6

  mysql-server:
    image: mysql:8.1
    restart: unless-stopped
    container_name: mysql-server
    ports:
      - 3306:3306
    networks:
     insm-net:
      ipv4_address: 192.168.1.5
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin', '--default-authentication-plugin=mysql_native_password']
    volumes:
    - db-data:/var/lib/mysql/

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    build:
      context: ./zabbix
    restart: unless-stopped
    container_name: zabbix-server-mysql
    networks:
     insm-net:
      ipv4_address: 192.168.1.10    
    ports:
      - 10051:10051
      - 10050:10050
    expose:
      - '10051'
      - '10050'
    volumes:
      - zabbix:/etc/zabbix/
      - ./zabbix_scripts:/usr/lib/zabbix/externalscripts  
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19
      ZBX_NODEADDRESS: 192.168.1.10
    links:
      - mysql-server:mysql

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    restart: unless-stopped    
    container_name: zabbix-web-nginx-mysql
    networks:
     insm-net:
      ipv4_address: 192.168.1.20    
    ports:
      - 80:8080
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19
    volumes:
      - nginx:/usr/share/zabbix
    links:
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    restart: unless-stopped    
    container_name: zabbix-agent
    networks:
      insm-net:
        ipv4_address: 192.168.1.11
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server-mysql 
      ZBX_HOSTINTERFACE: 192.168.1.11

  suricata:
    network_mode: "host"
    image: jasonish/suricata:latest
    build:
      context: ./suricata
    container_name: suricata
    cap_add: 
      - net_admin
      - net_raw
      - sys_nice
    stdin_open: true
    tty: true  
    volumes:
      - ./suricata/etc:/etc/suricata
      - ./suricata/var/log/suricata:/var/log/suricata
      - ./suricata/var/lib/suricata:/var/lib/suricata
     

